name: Deploy to heroku.

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Add a step to create or update the config.json file
      - name: Create config.json
        run: |
          echo '{
            "host": "${{ secrets.DB_HOST }}",
            "user": "${{ secrets.DB_USERNAME }}",
            "password": "${{ secrets.DB_PASSWORD }}",
            "database": "${{ secrets.DB_NAME }}"
          }' > configs/db_config.json

      # Your existing steps...
      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
